
spring:
  profiles:
    active: awsparamstore
  cloud:
    config:
      server:
        awsparamstore:
          region: ap-northeast-2
          endpoint: https://ssm.ap-northeast-2.amazonaws.com
          origin: aws::ssm::ap-northeast-2::440272560521::parameter
          prefix: sprig-boot-aws
          recursive: true
          decrypt-values: true
          max-results: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    profiles: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mySql.url}
    username: ${mySql.username}
    password: ${mySql.password}
    port: ${mySql.port}
  config:
    import: "optional:configserver:"
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      access-key: ${aws.access.key}
      secret-key: ${aws.secret.key}
      instance-profile: false
    s3:
      bucket: ${bucket.name}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false


jwt:
  secret-key: ${jwt.secret.key}
  access-token-expiration-minutes: 2880
  refresh-token-expiration-minutes: 5760


