spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    profiles: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}/danim?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&reconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    port: ${RDS_PORT}

  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    credentials:
      instance-profile: false
    s3:
      bucket: ${BUCKET_NAME}
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false

iam:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 400


